apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-b
  namespace: region-b
  labels:
    app: kafka-consumer
    region: region-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
      region: region-b
  template:
    metadata:
      labels:
        app: kafka-consumer
        region: region-b
    spec:
      serviceAccountName: kafka-consumer-sa
      containers:
      - name: kafka-consumer
        image: kafka-failover:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-headless.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "test-topic"
        - name: KAFKA_CONSUMER_GROUP
          value: "failover-consumer-group"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
